# Nameless Plugin configuration
# -----------------------------
# API URL
# This needs to be the full API URL, including API key
# For example http://yoursite.com/api/v1/API_KEY
api-url: ""

# Use registration?
# At the moment we bypass the option of registration in the
# website, so you can disable or enable it here.
# By default its enabled.
enable-registration: true

# Use reports?
# If true, a /report command will be added to report users ingame
# which will be added to the website's report system
# Valid values = true, false
enable-reports: true

# Enable join notifications?
# If true, players will be sent a notification message
# on join, containing the amount of alerts and private
# messages received
# Valid values = true, false
join-notifications: true

# Enable group synchronization?
# If true, you must set the permissions required for
# the players to be given ranks in the NamelessMC web
# setup. A GroupSyncPermissions.yml will be generated in order
# to set the permissions.
group-synchronization: false

# Enable Update Username?
# If true, players that has changed their username
# will be updated on the website.
# Valid values = true, false
update-username: false

# Enable UpdateChecker
# If true anyone with namelessmc.admin.updatenotify permission,
# will get notified when there is a new update,
# They will get notified when they join.
# Also there will be a msg displayed in console.
update-checker: true

# Enable https?
# If you have a ssl certificate, enable this option.
https: false

# DO NOT TOUCH! THIS WILL MESS UP YOUR CONFIG!
config-version: 1